import React, { useMemo, useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import {
  ArrowRight, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ChevronRight, CircleHelp,
  Clock3, Copy, ExternalLink, Filter, Globe2, LayoutGrid, MapPin, MessageCircle, MoreHorizontal,
  Search, Send, Settings2, ShieldCheck, Sparkles, UserPlus, Users, X, Loader2
} from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { companyProfileService } from '../../services/companyProfileService';
import { workspaceConversations, workspaceEvents, workspacePeople } from '../../data/userWorkspaceData';

const tabs = [
  { key: 'network', label: 'Network', icon: Users },
  { key: 'connections', label: 'Connections', icon: UserPlus },
  { key: 'card', label: 'Digital Card', icon: ShieldCheck },
  { key: 'team', label: 'Team & Department', icon: BriefcaseBusiness },
  { key: 'company', label: 'Company', icon: Globe2 },
  { key: 'events', label: 'Events', icon: CalendarDays },
  { key: 'messages', label: 'Messages', icon: MessageCircle },
  { key: 'settings', label: 'Settings', icon: Settings2 },
  { key: 'help', label: 'Help & Support', icon: CircleHelp }
];

const Surface = ({ children, className = '' }) => <div className={`bg-white border border-slate-100 rounded-2xl shadow-card ${className}`}>{children}</div>;
const Avatar = ({ initials, className = 'bg-indigo-100 text-indigo-700' }) => <div className={`w-10 h-10 rounded-xl flex items-center justify-center text-xs font-extrabold ${className}`}>{initials}</div>;
const Badge = ({ children, tone = 'indigo' }) => <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[10px] font-bold ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : 'bg-indigo-50 text-indigo-700'}`}>{children}</span>;

function Header({ title, description, icon: Icon }) {
  return <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3 mb-6"><div><div className="flex items-center gap-2 text-indigo-600 mb-2"><Icon className="w-4 h-4" /><span className="text-[10px] font-bold uppercase tracking-[0.18em]">Employee workspace</span></div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">{title}</h1><p className="text-xs text-slate-500 mt-1">{description}</p></div></div>;
}

function Network() {
  const [query, setQuery] = useState('');
  const [department, setDepartment] = useState('All departments');
  const filtered = workspacePeople.filter((person) => `${person.name} ${person.role} ${person.department} ${person.location}`.toLowerCase().includes(query.toLowerCase()) && (department === 'All departments' || person.department === department));
  return <><Header title="Network" description="Discover colleagues, connect with your community, and grow your professional network." icon={Users} /><Surface className="p-4 mb-5"><div className="flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search people, roles, skills..." className="w-full h-9 pl-9 pr-3 rounded-xl border border-slate-200 text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500" /></div><select value={department} onChange={(e) => setDepartment(e.target.value)} className="h-9 rounded-xl border border-slate-200 px-3 text-xs text-slate-600"><option>All departments</option><option>Design</option><option>Engineering</option><option>Marketing</option><option>People</option></select><button className="inline-flex items-center justify-center gap-2 h-9 px-4 rounded-xl bg-slate-50 text-xs font-bold text-slate-600"><Filter className="w-3.5 h-3.5" /> More filters</button></div></Surface><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{filtered.map((person) => <Surface key={person.id} className="p-5"><div className="flex items-start gap-3"><Avatar initials={person.initials} className={person.color} /><div className="flex-1 min-w-0"><div className="flex justify-between gap-2"><div><h3 className="text-sm font-bold text-slate-900">{person.name}</h3><p className="text-[11px] text-slate-500 mt-0.5">{person.role}</p></div><button className="text-slate-300 hover:text-slate-600"><MoreHorizontal className="w-4 h-4" /></button></div><div className="flex flex-wrap gap-2 mt-3"><span className="inline-flex items-center gap-1 text-[10px] text-slate-500"><BriefcaseBusiness className="w-3 h-3" />{person.department}</span><span className="inline-flex items-center gap-1 text-[10px] text-slate-500"><MapPin className="w-3 h-3" />{person.location}</span></div><div className="flex flex-wrap gap-1.5 mt-3">{person.skills.map((skill) => <Badge key={skill}>{skill}</Badge>)}</div><div className="flex gap-2 mt-4"><button className="flex-1 h-8 rounded-lg bg-indigo-600 text-white text-[11px] font-bold hover:bg-indigo-700">Connect</button><button className="h-8 px-3 rounded-lg border border-slate-200 text-slate-600 text-[11px] font-bold">View profile</button></div></div></div></Surface>)}</div>{filtered.length === 0 && <Surface className="p-12 text-center text-xs text-slate-400">No people match your search.</Surface>}<p className="text-[10px] text-slate-400 mt-5">People discovery is ready for the future team directory API. This view currently uses frontend-safe sample data because no employee network endpoint is exposed.</p></>;
}

function Connections() { return <><Header title="Connections" description="Manage incoming requests, sent invitations, and your professional connections." icon={UserPlus} /><div className="grid grid-cols-1 lg:grid-cols-3 gap-4">{[['Incoming requests', '2 waiting', 'Accept or review people who want to connect.'], ['Sent requests', '3 pending', 'Keep track of invitations you have sent.'], ['My connections', '24 people', 'Message and collaborate with your network.']].map(([title, count, text]) => <Surface key={title} className="p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-slate-900">{title}</h3><Badge tone="green">{count}</Badge></div><p className="text-[11px] text-slate-500 mt-2">{text}</p><button className="mt-6 inline-flex items-center gap-1 text-[11px] font-bold text-indigo-600">Open list <ArrowRight className="w-3 h-3" /></button></Surface>)}</div><Surface className="mt-5 p-5"><h3 className="text-sm font-bold text-slate-900 mb-4">Recent connection activity</h3>{workspacePeople.slice(0, 3).map((person, i) => <div key={person.id} className="flex items-center gap-3 py-3 border-b last:border-0 border-slate-50"><Avatar initials={person.initials} className={person.color} /><div className="flex-1"><p className="text-xs font-bold text-slate-800">{person.name}</p><p className="text-[10px] text-slate-500">{i === 0 ? 'Accepted your connection request' : 'You are connected'}</p></div><span className="text-[10px] text-slate-400">{i + 1}d ago</span></div>)}</Surface></>; }

function Card({ member, user }) { const slug = member?.profileId?.slug; const name = member?.name || user?.name || 'Your Name'; const link = slug ? `${window.location.origin}/p/${slug}` : `${window.location.origin}/me/profile`; const copy = async () => { await navigator.clipboard?.writeText(link); }; return <><Header title="Digital Card" description="Share a verified professional identity wherever you connect." icon={ShieldCheck} /><div className="grid grid-cols-1 lg:grid-cols-5 gap-5"><Surface className="lg:col-span-3 p-8 bg-gradient-to-br from-indigo-700 via-indigo-600 to-violet-600 text-white relative overflow-hidden"><Sparkles className="absolute right-6 top-6 w-5 h-5 text-indigo-200" /><div className="relative"><div className="w-16 h-16 rounded-2xl bg-white/15 border border-white/20 flex items-center justify-center text-2xl font-extrabold">{name.charAt(0)}</div><div className="mt-7"><div className="flex items-center gap-2"><h2 className="text-2xl font-extrabold">{name}</h2><CheckCircle2 className="w-4 h-4 text-emerald-300" /></div><p className="text-sm text-indigo-100 mt-1">{member?.designation || 'Your professional designation'}</p><p className="text-xs text-indigo-200 mt-5">{member?.companyId?.name || 'OneWinq Enterprise'}</p></div><div className="mt-12 pt-5 border-t border-white/15 text-xs text-indigo-100 break-all">{link}</div></div></Surface><div className="lg:col-span-2 space-y-4"><Surface className="p-5"><h3 className="text-sm font-bold text-slate-900">Card actions</h3><div className="space-y-2 mt-4"><button onClick={() => window.open(link, '_blank')} className="w-full h-10 rounded-xl bg-indigo-600 text-white text-xs font-bold inline-flex items-center justify-center gap-2"><ExternalLink className="w-4 h-4" />View public card</button><button onClick={copy} className="w-full h-10 rounded-xl border border-slate-200 text-slate-700 text-xs font-bold inline-flex items-center justify-center gap-2"><Copy className="w-4 h-4" />Copy profile link</button><button className="w-full h-10 rounded-xl border border-slate-200 text-slate-700 text-xs font-bold inline-flex items-center justify-center gap-2"><Sparkles className="w-4 h-4" />Download QR</button></div></Surface><Surface className="p-5"><h3 className="text-sm font-bold text-slate-900">Card style</h3><div className="grid grid-cols-3 gap-2 mt-4">{['Aurora', 'Classic', 'Minimal'].map((style, i) => <button key={style} className={`h-16 rounded-xl text-[10px] font-bold ${i === 0 ? 'bg-indigo-600 text-white ring-2 ring-indigo-200' : 'bg-slate-50 text-slate-600'}`}>{style}</button>)}</div></Surface></div></div><p className="text-[10px] text-slate-400 mt-5">QR download and sharing are wired to the existing public profile slug when available.</p></>; }

function Team({ member }) { const department = member?.departmentId?.name || 'Your Department'; return <><Header title="Team & Department" description="Stay connected to your department, projects, and announcements." icon={BriefcaseBusiness} /><div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><Surface className="lg:col-span-2 p-6"><div className="flex items-center justify-between"><div><Badge>Department</Badge><h2 className="text-xl font-extrabold text-slate-900 mt-2">{department}</h2><p className="text-xs text-slate-500 mt-1">Collaborate with the people shaping this function.</p></div><div className="w-12 h-12 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><Users className="w-5 h-5" /></div></div><div className="grid grid-cols-3 gap-3 mt-8">{[['Members', '18'], ['Active projects', '4'], ['Announcements', '6']].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-extrabold text-slate-900">{value}</p><p className="text-[10px] text-slate-500 mt-1">{label}</p></div>)}</div></Surface><Surface className="p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Department head</p><div className="flex items-center gap-3 mt-4"><Avatar initials="NI" className="bg-sky-100 text-sky-700" /><div><p className="text-xs font-bold text-slate-900">Nisha Iyer</p><p className="text-[10px] text-slate-500">People Operations</p></div></div><button className="mt-6 w-full h-9 rounded-xl border border-slate-200 text-xs font-bold text-slate-700">View all members</button></Surface></div><Surface className="mt-5 p-6"><h3 className="text-sm font-bold text-slate-900">Department updates</h3>{['New project workspace is available', 'Monthly department sync moved to Friday', 'Welcome two new teammates'].map((item, i) => <div key={item} className="flex gap-3 py-4 border-b last:border-0 border-slate-50"><div className="w-7 h-7 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center text-xs font-bold">{i + 1}</div><div><p className="text-xs font-semibold text-slate-800">{item}</p><p className="text-[10px] text-slate-400 mt-1">Posted {i + 1} day{i ? 's' : ''} ago</p></div></div>)}</Surface></>; }

function Company() {
  const [company, setCompany] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    companyProfileService.getPublicProfile()
      .then(setCompany)
      .catch(() => setCompany(null))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="py-20 flex items-center justify-center"><Loader2 className="w-6 h-6 text-indigo-400 animate-spin" /></div>;

  const name = company?.name || 'OneWinq Enterprise';
  const tagline = company?.tagline || 'A connected workplace where every employee can build a trusted digital identity.';
  const industry = company?.industry || 'Technology & SaaS';
  const sections = company?.dynamicSections || [];

  return <>
    <Header title="Company Profile" description="Explore your organization, our people, work, and values." icon={Globe2} />
    <Surface className="p-7 bg-gradient-to-r from-slate-900 to-indigo-900 text-white">
      <Badge tone="green">Verified organization</Badge>
      <h2 className="text-2xl font-extrabold mt-4">{name}</h2>
      <p className="text-sm text-indigo-100 max-w-2xl mt-2">{tagline}</p>
      <div className="flex flex-wrap gap-6 mt-7 text-xs text-indigo-200">
        {industry && <span>{industry}</span>}
        {company?.website && <><span>•</span><a href={company.website} target="_blank" rel="noreferrer" className="underline hover:text-white">{company.website}</a></>}
        {company?.location && <><span>•</span><span>{typeof company.location === 'string' ? company.location : [company.location?.city, company.location?.country].filter(Boolean).join(', ')}</span></>}
      </div>
    </Surface>
    {sections.length > 0 ? (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-5">
        {sections.map((section) => (
          <Surface key={section._id || section.title} className="p-5">
            <h3 className="text-sm font-bold text-slate-900">{section.title}</h3>
            <p className="text-[11px] text-slate-500 leading-relaxed mt-3">{section.content?.text || section.body || '—'}</p>
          </Surface>
        ))}
      </div>
    ) : (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-5">
        {[['Our mission', 'Make professional identity more human, portable, and trusted.'], ['What we build', 'Tools for teams, people, and meaningful professional connections.'], ['Our culture', 'Curious, inclusive, direct, and always learning together.']].map(([title, text]) => (
          <Surface key={title} className="p-5">
            <h3 className="text-sm font-bold text-slate-900">{title}</h3>
            <p className="text-[11px] text-slate-500 leading-relaxed mt-3">{text}</p>
          </Surface>
        ))}
      </div>
    )}
    {company?.contactEmail && (
      <Surface className="mt-4 p-5 flex items-center justify-between">
        <div><h3 className="text-sm font-bold text-slate-900">Get in touch</h3><p className="text-[11px] text-slate-500 mt-1">{company.contactEmail}</p></div>
        <a href={`mailto:${company.contactEmail}`} className="px-4 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold hover:bg-indigo-700 transition">Contact</a>
      </Surface>
    )}
  </>;
}

function Events() { const [registered, setRegistered] = useState([]); return <><Header title="Events" description="Discover company moments, learning sessions, and community gatherings." icon={CalendarDays} /><div className="flex gap-2 mb-5"><Badge>Upcoming</Badge><button className="text-[11px] font-semibold text-slate-500">Past events</button></div><div className="space-y-3">{workspaceEvents.map((event) => <Surface key={event.id} className="p-5"><div className="flex flex-col sm:flex-row sm:items-center gap-4"><div className="w-14 h-14 rounded-xl bg-indigo-50 text-indigo-600 flex flex-col items-center justify-center"><CalendarDays className="w-4 h-4" /><span className="text-[9px] font-bold mt-1">SEP</span></div><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><h3 className="text-sm font-bold text-slate-900">{event.title}</h3><Badge>{event.type}</Badge></div><div className="flex flex-wrap gap-3 mt-2 text-[10px] text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="w-3 h-3" />{event.date} · {event.time}</span><span className="inline-flex items-center gap-1"><MapPin className="w-3 h-3" />{event.location}</span></div><p className="text-[10px] text-slate-400 mt-2">Organized by {event.organizer}</p></div><button onClick={() => setRegistered((prev) => prev.includes(event.id) ? prev.filter((id) => id !== event.id) : [...prev, event.id])} className={`h-9 px-4 rounded-xl text-[11px] font-bold ${registered.includes(event.id) ? 'bg-emerald-50 text-emerald-700' : 'bg-indigo-600 text-white'}`}>{registered.includes(event.id) ? 'Registered' : 'Register'}</button></div></Surface>)}</div><p className="text-[10px] text-slate-400 mt-5">Registration state is frontend-only until an events endpoint is introduced.</p></>; }

function Messages() { const [selected, setSelected] = useState(workspaceConversations[0]); const [message, setMessage] = useState(''); return <><Header title="Messages" description="Keep conversations with colleagues and connected members in one place." icon={MessageCircle} /><Surface className="overflow-hidden grid grid-cols-1 md:grid-cols-3 min-h-[480px]"><div className="border-r border-slate-100"><div className="p-4 border-b border-slate-100"><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input placeholder="Search conversations" className="w-full h-9 pl-9 rounded-xl bg-slate-50 border-0 text-xs focus:outline-none" /></div></div>{workspaceConversations.map((conversation) => <button key={conversation.id} onClick={() => setSelected(conversation)} className={`w-full flex items-center gap-3 p-4 text-left border-b border-slate-50 ${selected.id === conversation.id ? 'bg-indigo-50/60' : 'hover:bg-slate-50'}`}><Avatar initials={conversation.initials} className={conversation.color} /><div className="flex-1 min-w-0"><p className="text-xs font-bold text-slate-800">{conversation.name}</p><p className="text-[10px] text-slate-400 truncate mt-1">{conversation.preview}</p></div>{conversation.unread > 0 && <span className="w-5 h-5 rounded-full bg-indigo-600 text-white text-[9px] font-bold flex items-center justify-center">{conversation.unread}</span>}</button>)}</div><div className="md:col-span-2 flex flex-col"><div className="p-4 border-b border-slate-100 flex items-center gap-3"><Avatar initials={selected.initials} className={selected.color} /><div><p className="text-xs font-bold text-slate-900">{selected.name}</p><p className="text-[10px] text-emerald-600">Connected</p></div></div><div className="flex-1 p-5 bg-slate-50/50"><div className="max-w-md"><div className="bg-white rounded-2xl rounded-tl-sm p-3 shadow-sm"><p className="text-xs text-slate-700">{selected.preview}</p></div><p className="text-[10px] text-slate-400 mt-2">{selected.time}</p></div></div><form onSubmit={(e) => { e.preventDefault(); setMessage(''); }} className="p-4 border-t border-slate-100 flex gap-2"><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write a message..." className="flex-1 h-9 px-3 rounded-xl border border-slate-200 text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500" /><button className="w-9 h-9 rounded-xl bg-indigo-600 text-white flex items-center justify-center"><Send className="w-4 h-4" /></button></form></div></Surface><p className="text-[10px] text-slate-400 mt-5">Messaging is UI-ready and intentionally does not send data until a connected-user messaging API is available.</p></>; }

function Settings() { const [saved, setSaved] = useState(false); return <><Header title="Settings & Privacy" description="Control your account, profile visibility, notifications, and security preferences." icon={Settings2} /><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{[['Account settings', 'Email, password, and account access'], ['Profile settings', 'Visibility, public profile, and identity details'], ['Notification settings', 'Choose the updates you want to receive'], ['Privacy settings', 'Control profile discovery and sharing'], ['Security settings', 'Sessions, password, and sign-in protection'], ['Preferences', 'Language, time zone, and display preferences']].map(([title, text], i) => <Surface key={title} className="p-5 flex items-center gap-4"><div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><Settings2 className="w-4 h-4" /></div><div className="flex-1"><h3 className="text-sm font-bold text-slate-900">{title}</h3><p className="text-[11px] text-slate-500 mt-1">{text}</p></div><ChevronRight className="w-4 h-4 text-slate-300" /></Surface>)}</div><Surface className="mt-5 p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold text-slate-900">Profile discoverability</h3><p className="text-[11px] text-slate-500 mt-1">Allow colleagues to find your public profile.</p></div><button onClick={() => setSaved(!saved)} className={`w-11 h-6 rounded-full p-1 transition ${saved ? 'bg-indigo-600' : 'bg-slate-200'}`}><span className={`block w-4 h-4 rounded-full bg-white transition ${saved ? 'translate-x-5' : ''}`} /></button></div></Surface></>; }

function Help() { return <><Header title="Help & Support" description="Find answers, contact support, or report an issue with your workspace." icon={CircleHelp} /><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[['Frequently asked questions', 'Browse answers to common account and profile questions.'], ['Contact support', 'Send a message to the OneWinq support team.'], ['Report an issue', 'Help us improve by sharing what went wrong.']].map(([title, text]) => <Surface key={title} className="p-5"><CircleHelp className="w-5 h-5 text-indigo-600" /><h3 className="text-sm font-bold text-slate-900 mt-4">{title}</h3><p className="text-[11px] text-slate-500 mt-2 leading-relaxed">{text}</p><button className="mt-5 text-[11px] font-bold text-indigo-600 inline-flex items-center gap-1">Open <ArrowRight className="w-3 h-3" /></button></Surface>)}</div><Surface className="mt-5 p-6"><h3 className="text-sm font-bold text-slate-900">Popular questions</h3>{['How do I publish my profile?', 'Who can see my digital card?', 'How do I update my contact details?'].map((question) => <div key={question} className="flex items-center justify-between py-4 border-b last:border-0 border-slate-50 text-xs font-semibold text-slate-700">{question}<ChevronRight className="w-4 h-4 text-slate-300" /></div>)}</Surface></>; }

export const UserWorkspacePage = () => { const location = useLocation(); const { member, user } = useAuth(); const key = location.pathname.split('/').pop(); const current = tabs.find((tab) => tab.key === key) || tabs[0]; const Component = { network: Network, connections: Connections, card: () => <Card member={member} user={user} />, team: () => <Team member={member} />, company: Company, events: Events, messages: Messages, settings: Settings, help: Help }[current.key]; return <div><div className="flex items-center gap-2 overflow-x-auto pb-4 mb-2 scrollbar-hide">{tabs.map((tab) => { const Icon = tab.icon; return <Link key={tab.key} to={`/me/${tab.key}`} className={`flex items-center gap-2 whitespace-nowrap px-3 py-2 rounded-xl text-[11px] font-bold transition ${current.key === tab.key ? 'bg-indigo-600 text-white shadow-sm' : 'bg-white border border-slate-100 text-slate-500 hover:text-indigo-600'}`}><Icon className="w-3.5 h-3.5" />{tab.label}</Link>; })}</div><Component /></div>; };
