import React, { useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3, Eye, Filter, MoreVertical, Search, Users, XCircle } from 'lucide-react';
import { useApprovals } from '../../hooks/useApprovals';
import { ReviewModal } from '../../components/profile-approvals/ReviewModal';
import { Badge } from '../../components/common/Badge';
import { Pagination } from '../../components/common/Pagination';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { EmptyState } from '../../components/common/EmptyState';
import { formatRelativeTime } from '../../utils/formatDate';

const statusLabels = { pending: 'Pending', approved: 'Approved', rejected: 'Rejected', changes_requested: 'Changes Requested' };

export const ProfileApprovalsPage = () => {
  const { approvals, pagination, params, error, loading, updateFilters, changePage, refetch } = useApprovals();
  const [selectedApproval, setSelectedApproval] = useState(null);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [search, setSearch] = useState('');
  const visibleApprovals = useMemo(() => {
    const query = search.trim().toLowerCase();
    return query ? approvals.filter((item) => `${item.memberId?.name || ''} ${item.memberId?.designation || ''} ${item.memberId?.departmentId?.name || ''}`.toLowerCase().includes(query)) : approvals;
  }, [approvals, search]);
  const counts = useMemo(() => approvals.reduce((result, item) => ({ ...result, [item.status]: (result[item.status] || 0) + 1 }), {}), [approvals]);
  const openReview = (approval) => { setSelectedApproval(approval); setReviewOpen(true); };
  const badge = (status) => status === 'approved' ? <Badge variant="green" dot>Approved</Badge> : status === 'rejected' ? <Badge variant="red" dot>Rejected</Badge> : status === 'changes_requested' ? <Badge variant="amber" dot>Changes Requested</Badge> : <Badge variant="blue" dot>Pending</Badge>;
  const statCards = [
    ['Pending Approvals', counts.pending || 0, Clock3, 'text-violet-600 bg-violet-50'],
    ['Approved', counts.approved || 0, CheckCircle2, 'text-emerald-600 bg-emerald-50'],
    ['Rejected', counts.rejected || 0, XCircle, 'text-rose-600 bg-rose-50'],
    ['Total Requests', pagination.totalItems || approvals.length, Users, 'text-sky-600 bg-sky-50']
  ];

  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">Profile Approval</h1><p className="mt-1 text-sm text-slate-500">Review and approve or reject profile changes requested by members.</p></div><button type="button" className="inline-flex items-center gap-2 self-start rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700"><Filter className="h-4 w-4" /> Filters</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(([label, value, Icon, color]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs text-slate-500">{label}</span><span className={`rounded-full p-2 ${color}`}><Icon className="h-4 w-4" /></span></div><div className="mt-2 text-2xl font-extrabold text-slate-900">{value}</div><div className="mt-1 text-[11px] text-slate-400">Current backend result set</div></div>)}</div>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-200">{[['pending', 'Pending'], ['approved', 'Approved'], ['rejected', 'Rejected'], ['', 'All']].map(([value, label]) => <button key={label} type="button" onClick={() => updateFilters({ status: value })} className={`whitespace-nowrap border-b-2 px-4 py-3 text-xs font-semibold ${params.status === value ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-slate-500'}`}>{label} ({value ? counts[value] || 0 : pagination.totalItems || approvals.length})</button>)}</div>
    {loading ? <div className="py-20"><LoadingSpinner message="Loading profile approval requests..." /></div> : error ? <div className="rounded-xl border border-rose-100 bg-rose-50 p-5 text-sm text-rose-700"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</div> : <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, role or department..." className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-xs outline-none focus:border-indigo-500" /></label><select onChange={(event) => updateFilters({ sort: event.target.value })} className="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600"><option value="newest">Sort: Newest</option><option value="oldest">Sort: Oldest</option></select></div>
        {visibleApprovals.length === 0 ? <EmptyState icon={CheckCircle2} title="No approval requests found" description="There are currently no profile submissions in this review state." /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Member</th><th className="px-3 py-3">Department</th><th className="px-3 py-3">Role</th><th className="px-3 py-3">Requested On</th><th className="px-3 py-3">Changes</th><th className="px-3 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 text-xs">{visibleApprovals.map((app) => <tr key={app._id} className={`cursor-pointer hover:bg-indigo-50/40 ${selectedApproval?._id === app._id ? 'bg-indigo-50/60' : ''}`} onClick={() => setSelectedApproval(app)}><td className="px-4 py-3"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-indigo-100 font-bold text-indigo-700">{app.memberId?.name?.charAt(0) || 'E'}</div><div><div className="font-bold text-slate-800">{app.memberId?.name || 'Employee'}</div><div className="text-[10px] text-slate-400">{app.submittedBy?.email || '-'}</div></div></div></td><td className="px-3 py-3 text-slate-600">{app.memberId?.departmentId?.name || 'General'}</td><td className="px-3 py-3 text-slate-600">{app.memberId?.designation || '-'}</td><td className="px-3 py-3 text-slate-500">{formatRelativeTime(app.submittedAt)}</td><td className="px-3 py-3"><span className="rounded-full border border-slate-200 px-2 py-1 text-[10px]">{Object.keys(app.draftSnapshot || {}).length || 0} changes</span></td><td className="px-3 py-3">{badge(app.status)}</td><td className="px-4 py-3 text-right"><div className="inline-flex items-center gap-1"><button type="button" onClick={(event) => { event.stopPropagation(); openReview(app); }} className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:text-indigo-600" title="View profile"><Eye className="h-4 w-4" /></button><button type="button" onClick={(event) => { event.stopPropagation(); setSelectedApproval(app); }} className="rounded-lg border border-slate-200 p-2 text-slate-500"><MoreVertical className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>}
        <Pagination currentPage={pagination.currentPage} totalPages={pagination.totalPages} totalItems={pagination.totalItems} itemsPerPage={pagination.itemsPerPage} onPageChange={changePage} label="requests" />
      </div>
      <aside className="hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:block">{selectedApproval ? <><div className="flex items-start justify-between"><div><div className="flex h-11 w-11 items-center justify-center rounded-full bg-indigo-100 text-lg font-bold text-indigo-700">{selectedApproval.memberId?.name?.charAt(0) || 'E'}</div><h2 className="mt-3 text-base font-bold text-slate-900">{selectedApproval.memberId?.name || 'Employee'}</h2><p className="text-xs text-slate-500">{selectedApproval.memberId?.designation || 'Employee'} · {selectedApproval.memberId?.departmentId?.name || 'General'}</p></div><button type="button" onClick={() => setSelectedApproval(null)} className="text-slate-400">×</button></div><div className="mt-5 rounded-xl bg-violet-50 p-3 text-xs text-violet-800">Requested {selectedApproval.submittedAt ? formatRelativeTime(selectedApproval.submittedAt) : 'recently'}</div><div className="mt-5"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Summary</h3><p className="mt-2 text-sm text-slate-700">{Object.keys(selectedApproval.draftSnapshot || {}).length || 0} fields updated</p></div><div className="mt-5">{badge(selectedApproval.status)}</div><button type="button" onClick={() => openReview(selectedApproval)} className="mt-6 w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-xs font-semibold text-white hover:bg-indigo-700">{selectedApproval.status === 'pending' ? 'Review Request' : 'View Changes'}</button></> : <div className="flex h-full min-h-[260px] items-center justify-center text-center text-sm text-slate-400">Select a request to preview profile changes.</div>}</aside>
    </div>}
    <ReviewModal isOpen={reviewOpen} onClose={() => setReviewOpen(false)} approval={selectedApproval} onSuccess={refetch} />
  </div>;
};
