import React from 'react';
import { Award, Briefcase, Mail, Phone, X } from 'lucide-react';
import { StatusBadge } from './StatusBadge';

const list = (value) => Array.isArray(value) ? value : [];

export const ProfilePreviewPanel = ({ approval, loading, onClose, onReview }) => {
  if (loading) return <div className="p-6 text-sm text-slate-500">Loading profile details…</div>;
  if (!approval) return <div className="flex min-h-[420px] items-center justify-center p-6 text-center text-sm text-slate-400">Select a request to review the complete submitted profile.</div>;
  const draft = approval.draftSnapshot || {}; const member = approval.memberId || {}; const links = draft.socialLinks || draft.socials || {};
  return <aside className="max-h-[calc(100vh-160px)] overflow-y-auto p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-900">{member.name || 'Employee'}</h2><p className="text-xs text-slate-500">{member.designation || '—'} · {member.departmentId?.name || 'General'}</p><div className="mt-2"><StatusBadge status={approval.status} /></div></div><button type="button" onClick={onClose} className="text-slate-400 hover:text-slate-700"><X className="h-4 w-4" /></button></div><section className="mt-5 space-y-4 text-sm"><Info title="Contact"><p><Mail className="mr-1 inline h-3.5 w-3.5" />{draft.email || approval.submittedBy?.email || 'Not provided'}</p>{draft.phone && <p className="mt-1"><Phone className="mr-1 inline h-3.5 w-3.5" />{draft.phone}</p>}</Info><Info title="About"><p className="whitespace-pre-wrap text-slate-600">{draft.about || draft.bio || 'No about information provided.'}</p></Info><Info title="Skills"><div className="flex flex-wrap gap-1">{list(draft.skills).length ? list(draft.skills).map((skill, index) => <span key={index} className="rounded-full bg-indigo-50 px-2 py-1 text-xs text-indigo-700">{skill.name || skill}</span>) : <span className="text-slate-500">No skills provided.</span>}</div></Info><Info title="Experience"><Entries icon={Briefcase} entries={draft.experience} /></Info><Info title="Projects"><Entries entries={draft.projects} /></Info><Info title="Achievements"><Entries icon={Award} entries={draft.achievements} /></Info><Info title="Social links"><div className="space-y-1 text-xs text-indigo-700">{Object.entries(links).filter(([, value]) => typeof value === 'string' && value).map(([name, value]) => <a key={name} href={value} target="_blank" rel="noreferrer" className="block truncate hover:underline">{name}: {value}</a>)}</div></Info>{approval.diffSummary?.length > 0 && <Info title="Previous data → Updated data"><div className="space-y-2 text-xs">{approval.diffSummary.map((change, index) => <div key={index} className="rounded-lg bg-slate-50 p-2"><strong className="capitalize">{change.field}</strong><p className="mt-1 text-slate-500">Previous: {String(change.oldValue ?? '—')}</p><p className="text-indigo-700">Updated: {String(change.newValue ?? '—')}</p></div>)}</div></Info>}</section>{approval.status === 'pending' && <button type="button" onClick={onReview} className="mt-6 w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-xs font-semibold text-white hover:bg-indigo-700">Review Request</button>}</aside>;
};
const Info = ({ title, children }) => <section><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{title}</h3>{children}</section>;
const Entries = ({ entries, icon: Icon }) => <div className="space-y-2">{list(entries).length ? list(entries).map((entry, index) => <div key={index} className="rounded-lg bg-slate-50 p-2 text-xs text-slate-600">{Icon && <Icon className="mr-1 inline h-3.5 w-3.5" />}<strong className="text-slate-800">{entry.title || entry.name || entry.position || String(entry)}</strong>{entry.company && <span> · {entry.company}</span>}{entry.description && <p className="mt-1">{entry.description}</p>}</div>) : <span className="text-xs text-slate-500">None provided.</span>}</div>;
